[project]
name = "doughjoe-sim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "sqlmodel>=0.0.27",
    "websockets>=15.0.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
